/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shapelibtest_JniTest */

#ifndef _Included_com_example_shapelibtest_JniTest
#define _Included_com_example_shapelibtest_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_shapelibtest_JniTest
 * Method:    helloWorld
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_shapelibtest_JniTest_helloWorld
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
