/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shapelibtest_ShapLibTest */

#ifndef _Included_com_example_shapelibtest_ShapLibTest
#define _Included_com_example_shapelibtest_ShapLibTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_shapelibtest_ShapLibTest
 * Method:    testRead
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_shapelibtest_ShapLibTest_testRead
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_shapelibtest_ShapLibTest
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_shapelibtest_ShapLibTest_test
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
